'use client';

import './globals.css'
import "tw-elements/dist/css/tw-elements.min.css";
import { Inter } from 'next/font/google'

import { motion, AnimatePresence  } from 'framer-motion'

import Header from './components/Header'
import Footer from './components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
       
          <motion.div
            initial={{ opacity: 0 }} // 初期状態
            animate={{ opacity: 1 }} // マウント時
            exit={{ opacity: 0 }}    // アンマウント時
          >
            <Header />
              {children}
            <Footer />
          </motion.div>
        
        </body>
    </html>
  )
}
